name=QA - SDL Regex
description=Check SDL QA regex rules against current OmegaT project

title=SDL QA Regex
errors_count=Errors found:
segment=Segment
rule=Rule
target=Target
source=Source
regex_source=Source regex
regex_target=Target regex
rule_type=Rule type
